spring:
  application:
    name: Sense Track

  datasource:
    url: jdbc:postgresql://localhost:5432/sensetrack
    username: postgres
    password: 30A20b10c.
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        type: trace

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web: TRACE